In [12]:
import torch
import numpy as np

In [51]:
#1. Создайте случайный FloatTensor размера 3x4x5
a = torch.rand(3, 4, 5)
a

tensor([[[0.2757, 0.7111, 0.1126, 0.2027, 0.5776],
         [0.0723, 0.8864, 0.7252, 0.3337, 0.5291],
         [0.1800, 0.9549, 0.5128, 0.3304, 0.6754],
         [0.5852, 0.5719, 0.1815, 0.2059, 0.4129]],

        [[0.6056, 0.8710, 0.3320, 0.6779, 0.8561],
         [0.1127, 0.0271, 0.9538, 0.0812, 0.6995],
         [0.7829, 0.6443, 0.9111, 0.4284, 0.3325],
         [0.1856, 0.3009, 0.7362, 0.5905, 0.8716]],

        [[0.9288, 0.0481, 0.0818, 0.1184, 0.8857],
         [0.5721, 0.8798, 0.2894, 0.8034, 0.7535],
         [0.9169, 0.7173, 0.9987, 0.6648, 0.8318],
         [0.9949, 0.0548, 0.1912, 0.6370, 0.5525]]])

In [52]:
# 2. Выведите его форму (shape)
a.shape

torch.Size([3, 4, 5])

In [53]:
a.type()

'torch.FloatTensor'

In [54]:
# 3. Приведите его к форме 6х10
a_reshape = a.reshape(6, 10)
a_reshape

tensor([[0.2757, 0.7111, 0.1126, 0.2027, 0.5776, 0.0723, 0.8864, 0.7252, 0.3337,
         0.5291],
        [0.1800, 0.9549, 0.5128, 0.3304, 0.6754, 0.5852, 0.5719, 0.1815, 0.2059,
         0.4129],
        [0.6056, 0.8710, 0.3320, 0.6779, 0.8561, 0.1127, 0.0271, 0.9538, 0.0812,
         0.6995],
        [0.7829, 0.6443, 0.9111, 0.4284, 0.3325, 0.1856, 0.3009, 0.7362, 0.5905,
         0.8716],
        [0.9288, 0.0481, 0.0818, 0.1184, 0.8857, 0.5721, 0.8798, 0.2894, 0.8034,
         0.7535],
        [0.9169, 0.7173, 0.9987, 0.6648, 0.8318, 0.9949, 0.0548, 0.1912, 0.6370,
         0.5525]])

In [55]:
# 4. Создайте случайный IntTensor размера 10
b = torch.IntTensor((torch.rand(size =(1, 10)) < 0.35).int())
b

tensor([[1, 0, 1, 1, 0, 0, 0, 1, 0, 1]], dtype=torch.int32)

In [56]:
# 5. Умножьте созданный FloatTensor на созданный IntTensor поэлементно
a_dot_b = torch.mul(a_reshape, b)
a_dot_b

tensor([[0.2757, 0.0000, 0.1126, 0.2027, 0.0000, 0.0000, 0.0000, 0.7252, 0.0000,
         0.5291],
        [0.1800, 0.0000, 0.5128, 0.3304, 0.0000, 0.0000, 0.0000, 0.1815, 0.0000,
         0.4129],
        [0.6056, 0.0000, 0.3320, 0.6779, 0.0000, 0.0000, 0.0000, 0.9538, 0.0000,
         0.6995],
        [0.7829, 0.0000, 0.9111, 0.4284, 0.0000, 0.0000, 0.0000, 0.7362, 0.0000,
         0.8716],
        [0.9288, 0.0000, 0.0818, 0.1184, 0.0000, 0.0000, 0.0000, 0.2894, 0.0000,
         0.7535],
        [0.9169, 0.0000, 0.9987, 0.6648, 0.0000, 0.0000, 0.0000, 0.1912, 0.0000,
         0.5525]])

In [57]:
# 6. Умножьте тензор матрично на себя, чтобы результат был размерности 6x6
# Подсказка: .dot может не подойти
AB_squared = a_dot_b @ a_dot_b.T
AB_squared.shape

torch.Size([6, 6])

In [58]:
# 7. Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)
from torch.autograd import Variable

x = Variable(torch.FloatTensor([1, 0.5, 2]), requires_grad = True)
y = x[0]**3 + x[1] - 75*x[2]
y.backward()
print(x.grad.sum().numpy())

-71.0


In [60]:
# 8. Создайте единичный тензор размера 5x6
ones_tensor = torch.ones(5, 6)
ones_tensor

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [62]:
# 9. Переведите его в формат numpy
ones_np = ones_tensor.numpy()
type(ones_np)

numpy.ndarray